# Generated by Django 2.1.4 on 2019-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='device',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fires',
            name='device',
            field=models.IntegerField(),
        ),
    ]
